services:
  db:
    image: postgres:18-alpine
    container_name: db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  cache:
    image: valkey/valkey:9-alpine
    container_name: cache
    command: ["valkey-server", "--appendonly", "yes"]
    volumes:
      - valkey-data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
    image: fapi-fastify:latest
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://app:app@db:5432/app
      VALKEY_HOST: cache
      VALKEY_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - backend
    expose:
      - "3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      update_config:
        order: start-first
      endpoint_mode: dnsrr

  proxy:
    image: haproxy:3.2-alpine
    container_name: proxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  postgres-data:
  valkey-data:
